name: make all test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache lib
      uses: actions/cache@v2
      with:
        path: |
          ~/lib
        key: ${{ runner.os }}-lib

    - name: make
      run: make -j
    - name: test
      run: make test
